# Generated by Django 5.0.4 on 2024-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RELEVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf_forms/%Y/%m/%d/')),
                ('Date_operation', models.CharField(max_length=250, null=True)),
                ('Date_valeur', models.CharField(max_length=250, null=True)),
                ('Reference', models.CharField(max_length=250, null=True)),
                ('Nature_operation', models.CharField(max_length=250, null=True)),
                ('Montant_debit', models.CharField(max_length=250, null=True)),
                ('Montant_credit', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
