# Generated by Django 5.0.4 on 2024-05-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='releve',
            name='Date_operation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='releve',
            name='Date_valeur',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='releve',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='app.date'),
        ),
    ]
