# Generated by Django 5.0.4 on 2024-05-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_date_alter_releve_date_operation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=250, null=True)),
                ('date', models.DateField(null=True)),
                ('amount', models.CharField(max_length=250, null=True)),
                ('date_f', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='app.date')),
            ],
        ),
    ]
