# Generated by Django 5.0.4 on 2024-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
