# Generated by Django 5.0.4 on 2024-05-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sms_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf_forms/%Y/%m/%d/')),
                ('service', models.CharField(max_length=250)),
                ('date', models.DateField(null=True)),
                ('amount', models.CharField(max_length=250)),
                ('date_f', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_infos', to='app.date')),
            ],
        ),
    ]
