# Generated by Django 5.0.4 on 2024-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_extractedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedinfo',
            name='date',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
