# Generated by Django 5.0.4 on 2024-05-18 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_extractedinfo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.date')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.extractedinfo')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.releve')),
                ('sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.sms')),
            ],
        ),
    ]
