# Generated by Django 5.0.4 on 2024-05-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_client_match_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='client',
        ),
    ]
